// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartHomeAPI.Migrations
{
	/// <inheritdoc />
	public partial class InitialCreate : Migration
	{
		/// <inheritdoc />
		protected override void Up(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.CreateTable(
				name: "Measures",
				columns: table => new
				{
					MeasurementId = table.Column<Guid>(type: "uuid", nullable: false),
					Value = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
					Timestamp = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_Measures", x => x.MeasurementId);
				});

			migrationBuilder.CreateTable(
				name: "Subscriptions",
				columns: table => new
				{
					MeasurementId = table.Column<Guid>(type: "uuid", nullable: false),
					Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: false),
					Unit = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
					MqttTopic = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
					ConverterName = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false, defaultValue: "default")
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_Subscriptions", x => x.MeasurementId);
				});
		}

		/// <inheritdoc />
		protected override void Down(MigrationBuilder migrationBuilder)
		{
			migrationBuilder.DropTable(
				name: "Measures");

			migrationBuilder.DropTable(
				name: "Subscriptions");
		}
	}
}
