<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<UserSecretsId>d7080a39-012a-4083-9054-d1d04e47b074</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="MQTTnet" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="NSwag.AspNetCore" />
		<PackageReference Include="oqo0.SwaggerThemes" />
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>

</Project>
